CREATE TABLE Account(
#Creating User Table
User_ID INT(10) PRIMARY KEY,
UserName VARCHAR(50) NOT NULL UNIQUE,
EmailAddress VARCHAR(50) NOT NULL UNIQUE,
Password VARCHAR(50) NOT NULL,
UserType VARCHAR(50) NOT NULL
);

CREATE TABLE Users (
#Creating Customer Table
Cus_ID INT(10) PRIMARY KEY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
CompanyName VARCHAR(110),
CompanyContact VARCHAR(50),
UserUser_ID INT(10) NOT NULL,
FOREIGN KEY (UserUser_ID) REFERENCES Account(User_ID)
);
